### PR TITLE
Implement an OpenGraphView

### PR DESCRIPTION
**Pull request by changxiangzhong**
Get the abstraction contents (including title, image, description & etc) of a given link.

When you copy a link to facebook/twitter, an abstraction card will be generated.

### CODE REVIEW

**Comment by 3lvis** [comment]
Should the `.idea` related files ignored by git?

https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore

**Comment by ealmdahl** [comment]
@3lvis it depends. It's not ignored by default, and apparently it may contain some data which might be relevant to the project. Anyway, this http://stackoverflow.com/questions/26336709/android-studio-should-the-entire-idea-directory-be-in-git-ignore suggests it's not necessary as long as we're all using gradle to build the projects. What do you think, @changxiangzhong ?

**Comment by 3lvis** [comment]
I thought it was IDE related files

**Comment by sindrenm** [comment]
Leaving the _.idea_ directory in the source control repository is oftentimes a real time-saver when someone else wants to import the project. It's also safe to assume that most people use Android Studio. And in later versions of Android Studio, the files in _.idea_ finally reference stuff **relatively** to the root, and not by a fixed path, which caused issues before. So it's safe to leave them there, but I agree that they technically don't belong there.

**Comment by changxiangzhong** [comment]
will make another pull request to remove them

**Pull request closed without merging**
